# Training configs
model_run: model_run_name

images:
  input_channels: 3
  resize: [1024, 1024]

# Directories
directories:
  train_labeled_dir: data/processed/train/labeled
  train_unlabeled_dir: data/processed/train/unlabeled
  val_dir:
  test_dir:
  output_dir:

# Optimizer
optim_name:
lr:
momentum:
beta1:
beta2:
nesterov: True

# Flexmatch
flexmatch:
  tau: 0.95
  mapping: linear
  warmup: True

# Model Architecture
model:
  architecture: DeepLabV3
  config:
    encoder_name: resnet18
    encoder_depth: 5
    encoder_weights: imagenet
    input_channels: 3
    classes: 5
  weight_decay:
  filter_bias_and_bn: True