# Training configs
model_run: model_run_name

images:
  input_channels: 3
  resize: [512, 512]

# Directories
directories:
  # train_labeled_dir: data/toy_dataset/train/labeleds
  train_labeled_dir: data/processed/train/labeled
  train_unlabeled_dir: data/toy_dataset/train/unlabeled
  val_dir: data/toy_dataset/val
  test_dir: data/toy_dataset/test
  output_dir: outputs
  checkpoint_dir: model_checkpoints

# Optimizer
training:
  epochs: 10
  # optim_name:
  lr: 0.001
  # momentum:
  # beta1:
  # beta2:
  nesterov: True

# Computation Device
device: cuda

batch_size:
  labeled: 2
  unlabeled: 2

# Flexmatch
flexmatch:
  tau: 0.95
  mapping: linear
  warmup: True

# Model Architecture
model:
  architecture: UNET
  config:
    encoder_name: resnet18
    encoder_depth: 5
    encoder_weights: imagenet
    input_channels: 3
    classes: 12
  # weight_decay:
  filter_bias_and_bn: True

metadata:
  norm_path: metadata/dataset_norm.json