# Training configs
model_run: model_run_name

images:
  input_channels: 3
  resize: [1024, 1024]

# Directories
directories:
  train_labeled_dir: data/toy_dataset/train/labeled
  train_unlabeled_dir: data/toy_dataset/train/unlabeled
  val_dir: data/processed/val
  test_dir: data/processed/test
  output_dir: outputs
  chkpt_dir: model_checkpoints

# Optimizer
training:
  epochs: 10
  optim_name:
  lr:
  momentum:
  beta1:
  beta2:
  nesterov: True

batch_size:
  labeled: 2
  unlabled: 2

# Flexmatch
flexmatch:
  tau: 0.95
  mapping: linear
  warmup: True

# Model Architecture
model:
  architecture: DeepLabV3
  config:
    encoder_name: resnet18
    encoder_depth: 5
    encoder_weights: imagenet
    input_channels: 3
    num_classes: 5
  weight_decay:
  filter_bias_and_bn: True